include:
  - first
  - ntp
  - mysql-install
  - rabbitmq-install
  - keystone-install
  - keystone-setup
  - keystone-setup
  - keystone-endpoint
  - osclients
  - openrc
  - glance-install
  - neutron-install
