include:
  - common.salt-minion.util-update
  - common.salt-minion.virtwhat
  - common.salt-minion.dateutil
  - common.salt-minion.mako
  - common.salt-minion.msgpack-pure
  - common.salt-minion.msgpack-python
  - common.salt-minion.pyinotify
  - common.salt-minion.no-auto-start
  - common.salt-master.pygit2
  - common.salt-master.psutil
  - common.salt-minion.glance
