#!/bin/bash
if [[ -e /etc/update-motd.d/20-virl ]]; then
  rm /etc/update-motd.d/20-virl
fi
touch /etc/update-motd.d/20-virl
chmod +x /etc/update-motd.d/20-virl
exec &>> /etc/update-motd.d/20-virl
mgmt=$(route | grep default | awk '{print $(NF)}')
maddr=$(ip addr show dev $mgmt | awk '$1 == "inet" { sub("/..", "", $2); print $2}')

echo "#!/bin/bash"
echo "printf \"\\n_________ Virtual Internet Routing Labs __________\\n\\\n\""
echo "printf \"To manage this server please use the User Workspace\\n\""
echo "printf \"Manager (UWM) interface at:\\n\\n\""
echo "printf \"http://$maddr\\n\\n\""
echo "printf \"The default credentials are 'uwmadmin' / 'password'\\n\\n\""
echo "printf \"Server Interfaces:\\n\\n\""

ifquery --list | egrep -v lo | sort | while read intf
do
ipadr=$(ip addr show dev $intf |awk '$1 == "inet" { sub("/..", "", $2); print $2}')
   ip link show $intf > /dev/null 2>&1
        if [ $? -ne 0 ] ; then
        echo "printf \"$intf is down\\n\""
        else
        echo "printf \"$ipadr ($intf)\\n\""
        fi
done
echo "printf \"\\n\""
echo "printf \"\\n\""