include:
  - virl.openrc
  - virl.ank
  - virl.std
  - virl.guest
  - virl.routervms.iol
  - virl.routervms.iol2
  - virl.routervms.iosv
  - virl.routervms.iosvl2
  - virl.routervms.lxc_server
  - virl.routervms.lxc_iperf
  - virl.routervms.lxc_routem
  - virl.routervms.lxc_ostinato
